backend:
  name: github
  repo: quieschristopher/web-CEALTECH
  branch: main

media_folder: "productos/{{collection}}/{{slug}}"
public_folder: "/productos/{{collection}}/{{slug}}"

collections:
  - name: "gamer"
    label: "Laptops Gamer"
    folder: "productos/gamer"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index.md"
    identifier_field: "title"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - {
          label: "Imagen principal",
          name: "main_image",
          widget: "image",
          default: "{{slug}}.jpg"
        }

  - name: "oficina"
    label: "Laptops de Oficina"
    folder: "productos/oficina"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index.md"
    identifier_field: "title"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - {
          label: "Imagen principal",
          name: "main_image",
          widget: "image",
          default: "{{slug}}.jpg"
        }

  - name: "convertible"
    label: "Laptops Convertibles"
    folder: "productos/convertible"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index.md"
    identifier_field: "title"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - {
          label: "Imagen principal",
          name: "main_image",
          widget: "image",
          default: "{{slug}}.jpg"
        }