backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

site_url: ""

collections:
  - name: "laptops"
    label: "Laptops"
    folder: "content/laptops"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Precio (S/)", name: "price", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Económicas","Intermedias","Touch y Convertibles","Gamer"] }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imágenes", name: "images", widget: "list", field: { label: "Imagen", name: "image", widget: "image" } }